# Configuration for pr-watcher-notifier
"edx/*":
  patterns:
    - "decisions/*.rst"
    - "decisions/*.md"
    - "*/decisions/*.rst"
    - "*/decisions/*.md"
    - "docs/*.rst"
    - "docs/*.md"
    - "docs/*/*.rst"
    - "docs/*/*.md"
    - "*/docs/*.rst"
    - "*/docs/*.md"
    - "*/docs/*/*.rst"
    - "*/docs/*/*.md"
    - "oeps/*.rst"
    - "oeps/*.md"
  recipients:
    # The Google Group for people who want email.
    # The #adr-notifications channel in the Open edX Slack.
    # "s5c2n2m2v2t0b2l2@openedx.slack.com" is on the ggroup.
    - "adr-notifications@googlegroups.com"
  subject: "Change in {{repo}}: {{pr.title}}"
  body: adr-body.txt
